#!/usr/bin/env sh

IS_PUBLISHED_VERSION=`git describe --tags --exact-match 2>/dev/null`

# NODE_DEFACTO_VERSION is passed to SnapCI build from Travis
if [ -z "$NODE_DEFACTO_VERSION" ]; then
    NODE_DEFACTO_VERSION=`cat package.json | grep '"version"' | sed -E -e 's/.*"version": "([^"]*)",/\1/'`
fi

# We don't set the version suffix on tagged (published) builds
if [ -n "$TRAVIS_BUILD_NUMBER" -a -z "$IS_PUBLISHED_VERSION" ]; then
    NODE_DEFACTO_VERSION="NODE_DEFACTO_VERSION-beta.$TRAVIS_BUILD_NUMBER"
fi

npm install

NODE_DEFACTO_VERSION=$NODE_DEFACTO_VERSION node_modules/grunt-cli/bin/grunt "$@"
