#!/bin/sh

set -e

PUBLISH=$1

echo "Deploying to npm (PUBLISH=$PUBLISH)..."

if [ "$PUBLISH" != "true" ]; then
    # Test npm publish to detect issues before the production publish
    # I've been surprised by Travis-related errors before
    mv package.json package.json.orig
    sed -E -e 's/"name": "node-defacto"/"name": "node-defacto-dev"/' package.json.orig > package.json
fi

dpl --provider=npm --email=brandon.byars@gmail.com --api-key=$NPM_API_KEY --skip-cleanup
